# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
pt:
  languageCode: pt-br
  contentDir: content/pt
  title: LabUAI
  params:
    description: Portuguese (Brazil)
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Sobre
        url: aboutus
        weight: 20
      - name: Membros
        url: members
        weight: 30
      - name: Projetos
        url: projects
        weight: 40
      - name: Datasets
        url: datasets
        weight: 50
      - name: Contato
        url: contact
        weight: 60
